site_name: 'RiskScanner 文档'
site_url: 'https://docs.riskscanner.io'
site_description: 'RiskScanner 文档'
site_author: 'maguohao'

repo_name: 'GitHub Star'
repo_url: 'https://github.com/riskscanner/riskscanner.git'
edit_uri: ''

theme:
  name: 'material'
  logo: 'img/logo.ico'
  favicon: 'img/facio.ico'
  language: 'zh'
  highlightjs: true
  feature:
    tabs: true
  hljs_languages:
    - yaml
    - django
  palette:
    accent: 'red'
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - header.autohide
  font: false
  custom_dir: 'theme'

nav:
  - 总体介绍: index.md
  - 安装配置:
      - 快速安装: installation/setup_by_fast.md
      - 升级文档: installation/upgrade/upgrade.md
  - 系统架构: system_arch.md
  - 用户手册:
      - 使用流程: user_manual/process.md
      - 系统设置: user_manual/settings.md
      - 扫描规则: user_manual/rule.md
      - 云账号: user_manual/account.md
      - 扫描结果: user_manual/resource.md
      - 首页: user_manual/dashboard.md
  - 消息通知:
      - 开启企业微信通知: tutorial/weixin_settings.md
      - 开启钉钉消息通知: tutorial/dingtalk_settings.md
  - 开发文档: dev_manual.md
  - 常见问题:
      - 解决云账号校验失败问题: question/account.md
      - 如何自定义规则: question/rule.md
      - 自定义阿里云监控规则示例: question/example.md
  - 关于:
      - 更新说明: about/changelog.md
      - 联系我们: about/contact.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  riskscanner:
    version: v1.3.1
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/riskscanner
    - icon: fontawesome/solid/envelope
      link: mailto:support@fit2cloud.com
    - icon: fontawesome/brands/skype
      link: tel://400-052-0755
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=yro3zdvticm8J4tdA5Dw20dh028NKeap&jump_from=webapi

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2014-2021 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>
google_analytics:
plugins:
    - search
    - macros
